obstacles_layer_g:
  observation_sources: laser_scan_sensor 
  laser_scan_sensor: {sensor_frame: laser_frame, data_type: LaserScan, topic: laser/scan, marking: true, clearing: true}

inflater_layer_g:
  inflation_radius: 0.2 
  cost_scaling_factor: 10.0
  lethal_cost_threshold: 200

plugins:
- {name: static_map, type: "costmap_2d::StaticLayer"} 
#- {name: obstacles_layer_g, type: "costmap_2d::ObstacleLayer"} #VoxelLayer"} ObstacleLayer
- {name: inflater_layer_g, type: "costmap_2d::InflationLayer"}

recovery_behaviors:
  - name: conservative_reset
    type: clear_costmap_recovery/ClearCostmapRecovery