obstacles_layer:
  observation_sources: laser_scan_sensor 
  laser_scan_sensor: {sensor_frame: laser_frame, data_type: LaserScan, topic: laser/scan, marking: true, clearing: true, min_obstacle_height: 0.0, max_obstacle_height: 5.0, obstacle_range: 6.0, raytrace_range: 7.0, inf_is_valid: true}


inflater_layer:
  inflation_radius: 0.4
  cost_scaling_factor: 10.0
  lethal_cost_threshold: 200


plugins:
- {name: obstacles_layer, type: "costmap_2d::VoxelLayer"} 
