max_planning_retries: 5
planner_patience: 10
number_of_recovery_behaviors: 3
planner_frequency: 5
controller_frequency: 10
allow_unknown: false
controller_patience: 3.0
oscillation_timeout: 10.0
oscillation_distance: 0.2
recovery_behaviors:
  - name: conservative_reset
    type: clear_costmap_recovery/ClearCostmapRecovery

conservative_reset:
  reset_distance: 5